# -*- coding: utf-8 -*-
"""finalProject_mongo_db.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iV5HzlPEduqu1VsxM0ieArOFICZZNNgf
"""

!pip install pymongo
!pip install python-dotenv


"""# MongoDB Python Connection Example

This Python script demonstrates how to connect to a MongoDB Atlas cluster, select a database and collection, and fetch all documents from the collection.

---

# MongoDB Python Connection Explanation

This Python script demonstrates how to connect to a MongoDB Atlas cluster, verify the connection, select a database and collection, and retrieve all documents from the collection.

First, the script imports the necessary modules from the `pymongo` library: `MongoClient`, which is used to establish a connection to the MongoDB server, and `ServerApi`, which specifies the server API version to ensure compatibility with MongoDB Atlas.

Next, the script defines a connection URI, which includes the username, password, cluster address, and optional parameters such as retryable writes and the application name. Using this URI, a `MongoClient` object is created with the specified server API version.

To confirm that the connection to the database is successful, the script sends a `ping` command to the MongoDB server. If the server responds, a success message is printed. If the connection fails, any exception is caught and displayed.

After the connection is established, the script selects a specific database and collection within that database. In this case, the database is named `final_project` and the collection is named `microsoft_attack`.

Finally, the script retrieves all documents from the collection using the `find` method. The query is empty to fetch all entries, and the `_id` field is excluded from the results. The returned cursor is converted into a Python list for easy manipulation and further analysis.

This workflow provides a complete process for connecting to a MongoDB Atlas cluster, verifying the connection, accessing a specific database and collection, and retrieving data for subsequent processing or conversion into a DataFrame.

---
## Code Breakdown

```python
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

"""

from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi
from dotenv import load_dotenv
import os


# טען את הערכים מקובץ .env
load_dotenv()

user = os.getenv("MONGO_USER")
password = os.getenv("MONGO_PASS")
host = os.getenv("MONGO_URI")

uri = f"mongodb+srv://{user}:{password}@{host}/?retryWrites=true&w=majority&appName=Cluster0"

# יצירת client והתחברות
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)


# בוחרים מסד ו-collection
db = client["final_project"]                 # שם ה-database
collection = db["microsoft_attack"]          # שם ה-collection

# מושכים את כל הדוקומנטים (בלי ה-_id)
data = list(collection.find({}, {"_id": 0}))

data = list(collection.find({}, {"_id": 0}))

import pandas as pd
def create_dataframe(data:list):
  df = pd.DataFrame(data)
  return df
def run_query(query:dict):
  mongoDB_query_result = list(collection.find(query, {"_id": 0}))
  return create_dataframe(mongoDB_query_result)

df_data = create_dataframe(data)
df_data.head(4)

print(f'Impact value : {collection.distinct("Impact")[3]} , {collection.distinct("Impact")[4]} , Day : {collection.distinct("Day")[3]}')

print(f'Affected Component : {collection.distinct("Affected Component")[9]}' 	)

# שאילתה 1 – Day = 9 ו־Impact מסוים
query1 = {
    "Day": 9,
    "Impact": {"$in": ["Information Disclosure", "Not a Vulnerability"]}
}

# שאילתה 2 – Year > 2011, Reboot = Maybe, ו־Affected Component מסוים
query2 = {
    "Year": {"$gt": 2011},
    "Reboot": {"$in": ['Maybe']},
    "Affected Component": collection.distinct("Affected Component")[9]
}

# שאילתה 3 – Severity = Critical ו־Month < 6
query3 = {
    "Severity": "Critical",
    "Month": {"$lt": 6}
}

# שאילתה 4 – CVEs מכיל מחרוזת מסוימת ו־Day = 8
query4 = {
    "CVEs": {"$regex": "CVE-2013-3128"},
    "Day": 8
}

queries = [query1, query2, query3, query4]
dfs = {}

for i, q in enumerate(queries, 1):
    df = run_query(q)
    dfs[f"query{i}"] = [q,df]

print(f'query: \n {dfs["query1"][0]}')
print(dfs["query1"][1].shape)
dfs["query1"][1].head(2)

print(f'query: \n {dfs["query2"][0]}')
print(dfs["query2"][1].shape)
dfs["query2"][1].head(2)

print(f'query: \n {dfs["query3"][0]}')
print(dfs["query3"][1].shape)
dfs["query3"][1].head(2)

print(f'query: \n {dfs["query4"][0]}')
print(dfs["query4"][1].shape)
dfs["query4"][1].head(2)
